### ISSUE TITLE
Suggestion to use the graph object to collect data

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-scenesfrancophones#1]
https://github.com/culturecreates/artsdata-planet-scenesfrancophones/blob/4c79a94ad2a0a7fb2deb4db09aa3a9259e86367b/main.rb#L38C3-L47C6

In the code below, you can use the graph object to collect data.

```
  entity_urls.each do |entity|
    graph = RDF::Graph.new
    begin
      graph << RDF::Graph.load(entity)
      json_ld_data = graph.dump(:jsonld)
      entity_data << JSON.parse(json_ld_data)
    rescue StandardError => e
      puts "Error loading RDF from #{entity}: #{e.message}"
    end
  end
```
can become
```
  entity_urls.each do |entity|
    begin
      graph << RDF::Graph.load(entity)
    rescue StandardError => e
      puts "Error loading RDF from #{entity}: #{e.message}"
    end
  end
```
and be sure to place  `graph = RDF::Graph.new` outside the main loop.  You don't need your `entity_data` variable. And at the end you can dump using` graph.dump(:jsonld)`.

**Comment by dev-aravind** [comment]
@saumier I've updated the code to use the graph object to collect data. Please review [this](https://github.com/culturecreates/artsdata-planet-scenesfrancophones/pull/2)

**Comment by saumier** [comment]
@dev-aravind Please see my comments in the PR.
