### ISSUE TITLE
New Scenesfrancophones.ca Endpoints

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-scenesfrancophones#16]
Scenesfrancophones.ca has changed the way they published their structured data.

Please remove the old way from the repo. The issue you mentioned at today's standup regarding a workflow failure when the data is not updated, please document this in issue #17 so I can follow along. I'd you to document the current behaviour, your fix and the new behaviour. Then we can discuss the expected behaviour of what should happen when there is no update to the data. My first impression is that if the data has no change (no diff in the commit) then it should not be published to Artsdata.

The new way is to provide an endpoint with all events and another endpoint with all places in JSON-LD.  I think this can be done directly in the workflow using curl, but I'll leave that up to you.

Please fetch the JSON-LD here:
Artifact scenesfrancophones-events:
https://scenesfrancophones.ca/donneesouvertes/evenements.json

Artifact scenesfrancophones-places (new):
https://scenesfrancophones.ca/donneesouvertes/lieux.json

Artifact scenesfrancophones-artists
https://scenesfrancophones.ca/donneesouvertes/artistes.json

Artifact scenesfrancophones-organizers
leave blank for now

For now there should be no transformations.

**It is very important to keep the SAME artifact names like [scenesfrancophones-events](https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Fartsdata-planet-scenesfrancophones%2Fscenesfrancophones-events).

You can leave Artist and Organizer empty for now.

Then Frédéric will review the data and get back to us with feedback.

Tasks
=====

- [x] Remove old way from repo
- [x] Artifact scenesfrancophones-events 
- [x] Artifact scenesfrancophones-places 
- [x] Artifact scenesfrancophones-artists
- [ ] Gregory to ask Frederik to review data in Artsdata

**Comment by dev-aravind** [comment]
@saumier The data is now available in Artsdata for you to review. [Events](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/query/show?title=Event%20entities%20in%20scenesfrancophones-events%20%283178%20triples%29&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-scenesfrancophones/scenesfrancophones-events) and [Places](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/query/show?title=Place%20entities%20in%20scenesfrancophones-places%20%281724%20triples%29&sparql=list_places&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-scenesfrancophones/scenesfrancophones-places) look fine but the artists data has type as "PerformingGroup", so it is not showing up in Artsdata. Let me know if you face any issues.

**Comment by saumier** [comment]
@dev-aravind This is great. Frederic at CAPACOA was very happy to see the data loaded. Thx.
