### ISSUE TITLE
Workflow fails when no change in data

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-scenesfrancophones#17]
Workflow fails when the data is not updated.

Behaviour before fix
========
```
Run git config --local user.email "actions@github.com"
From https://github.com/culturecreates/artsdata-planet-scenesfrancophones
 * [new branch]      feature/issue-6 -> origin/feature/issue-6
 * [new branch]      feature/issue-7 -> origin/feature/issue-7
 * [new branch]      feature/issue-8 -> origin/feature/issue-8
Already up to date.
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.bundle/
	vendor/

nothing added to commit but untracked files present (use "git add" to track)
Error: Process completed with exit code 1.
```

Fix
====
https://github.com/culturecreates/artsdata-planet-scenesfrancophones/commit/d674abc7291f6e126dce9a9d2d3123d7da033c9e

Behaviour after fix
=============
If the data has no change, the git commit into the repository step and the artsdata-push job are skipped. 

Discussion
========
 My first impression is that if the data has no change (no diff in the commit) then it should not be published to Artsdata.

**Comment by dev-aravind** [comment]
@saumier The data now is not commited and also not pushed to artsdata if there are no changes.
