### ISSUE TITLE
Setup Ruby dev environment

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-scenesfrancophones#3]
While working on artsdata-planet-scenesfrancophone let's setup our Ruby dev environment so we can collaborate. See https://github.com/culturecreates/artsdata-orion/issues/11 for examples of what to put in these files. 

- [x] .rvmrc in source control
- [x] .ruby-version in source control
- [x] Gemfile in source control 
- [x] Gemfile.lock in source control

**Comment by dev-aravind** [comment]
I've updated the code to add these files and also ran the workflow to get details about the events. You can test it out using these workflow variables:

Page URL to loop pages: https://scenesfrancophones.ca/spectacles?page=
Base URL: https://scenesfrancophones.ca
Entity html tag: div.title
File Name: events.jsonld

**Comment by saumier** [comment]
@dev-aravind Looking great. There were a couple of small changes to the Gemfile.lock file so I committed my Gemfile.lock. I would like this to be stable, meaning there should not be any change to the Gemfile.lock after running `bundle install`. Please do a pull of the main branch and `bundle install`. If the Gemfile.lock changes please let me know. Then I will close this issue.

**Comment by dev-aravind** [comment]
@saumier The bundle install command adds new dependencies which are needed for the ruby project to run in linux. What do you suggest?

**Comment by saumier** [comment]
@dev-aravind Please do a pull of the main branch and then `bundle install` and then commit the changes to main branch if it changed. I want to know if the Gemfile.lock changes when we each do  `bundle install` and I am expecting that it does not.
Gemfile.lock is used as a snapshot of all your required gems and their dependencies and we should both have the same Gemfile.lock even though I am running on MacOS and you on Linux.

**Comment by dev-aravind** [comment]
@saumier I've updated the lockfile. Please look into it and let me know.

**Comment by saumier** [comment]
@dev-aravind I ran `bundle install` and there was no change to the Gemfile.lock. All good.  Now a new developer should be able to git clone the repo, cd into the directory to generate the gemset and do a  `bundle install` to get the exact same versions of the libraries we are using.
