### ISSUE TITLE
Schedule crawl of scenesfrancophones.ca

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-scenesfrancophones#6]
The scraping must be triggered using a GitHub workflow. New versions of the scraped output files should be committed to the main branch in the directory `output` . For example, the file`output/spectacles.jsonld` should be updated after each scrape of https://scenesfrancophones.ca/spectacles and committed to the main branch.

Frequency of scheduled scraping:

- Events (spectacles) are weekly
- Organizers monthly
- Artists monthly

Measure of done
===========
The 3 workflows are setup and tested by running manually.

**Comment by dev-aravind** [comment]
@saumier I added 3 workflows to generate the JSON-LD and also updated the schedule in which they trigger.

**Comment by saumier** [comment]
@dev-aravind Great. I made one change to make the artifact names different.  It is very important that the artifact names are different because each version of an artifact replaces the previous version.
