### ISSUE TITLE
Send scenesfrancophones graphs to Artsdata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-scenesfrancophones#7]
Send each dump of the crawled graph to Artsdata by calling the API of the Artsdata Databus:

POST http://api.artsdata.ca/databus/
- artifact: {scenesfrancophones-events | scenesfrancophones-artists | scenesfrancophones-organizers }
- comment: {scenesfrancophones.ca + events | artists | organizers}
- group: {name of repo}
- version: {dump date/time}
- downloadUrl: {complete path to file including http. Must be accessible from a web browser)
- downloadFile: {events.jsonld | artsits.jsonld | organizers.jsonld}
- reportCallbackUrl: {keep default}
- shacl: {leave blank}

Example:

```
{
"artifact": "scenesfrancophones-events",
"comment": "Scenesfrancophones.ca Events",
"publisher": "${{ secrets.PUBLISHER_URI_GREGORY }}",
"group": "${{ github.event.repository.name }}",
"version": "${{ steps.version.outputs.dumpdate }}",
"downloadUrl": "https://raw.githubusercontent.com/culturecreates/artsdata-planet-scenesfrancophones/main/output/events.jsonld",
"downloadFile": "events.jsonld",
"reportCallbackUrl": "https://huginn-staging.herokuapp.com/users/1/web_requests/273/databus"
} 
```

Ask Gregory about the other options if needed.

Measure of done
============
Scripts are tested manually and the graph appear in Artsdata whenever new data is crawled from the website.

**Comment by saumier** [comment]
@dev-aravind I created a separate example [workflow](https://github.com/culturecreates/artsdata-planet-scenesfrancophones/blob/main/.github/workflows/push-dump-to-artsdata.yml) for sending to the Artsdata Databus API. You can use this and only change the name of the artifact for each of the different dumps: events or people or organizations.  This POST to the Artsdata API is a candidate to turn into a Ruby Gem and GitHub Action later on when we refactor these ETL pipelines. Since this is on a tight deadline, please don't worry about duplicate code in the workflows.

**Comment by saumier** [comment]
@dev-aravind To complete this issue, please have the 3 workflows that scrape the data then call the respective push to Artsdata workflow. The data should be crawled and pushed automatically after the crawl.

**Comment by dev-aravind** [comment]
@saumier I updated the workflow to trigger the artsdata push automatically after the crawl. Please look into it and let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind What was the expiry date of the PAT you are using in the workflows? I am not sure this is good for long term maintenance. Is there another way that takes into account long term maintenance, ease of understanding for a new developer, best practices, and reduced dependencies?

**Comment by saumier** [comment]
I am making some changes to the workflow.

Removing warning messages. 
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-ruby@v1.
```

Fixing a few issues such as:
```
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
```
* updating actions/checkout@v2 --> v4
* Adding bundler-cache: true
* removing ruby-version: '3.1' from workflow because the version is already set in the .ruby-version file

**Comment by saumier** [comment]
@dev-aravind I am assigning back to you so you can make another pass at reusing workflows without needing to use a PAT.  Please look into this doc which at first glance seems to provide a different approach than the repository_dispatch you used https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by saumier** [comment]
@dev-aravind I made a lot of small changes to the workflows. Please take a look. Now that I added bundler-cache: true to speed up the workflow (by using a cache) it is important to use "bundle exec" in front of the ruby command so the correct gems are used.  Also, I changed **actions**/setup-ruby to **ruby**/setup-ruby which is such a small but important change I wanted to call it out.

**Comment by saumier** [comment]
@dev-aravind Please see https://github.com/culturecreates/artsdata-planet-scenesfrancophones/issues/7#issuecomment-1877217654 for the work needed before I close this issue.

**Comment by dev-aravind** [comment]
@saumier The PAT was set to have no expiry as that seemed more logical. But as per [your comment](https://github.com/culturecreates/artsdata-planet-scenesfrancophones/issues/7#issuecomment-1877217654), I updated the workflows to make the artsdata push workflow reusable and to be used by the 3 crawl workflows. Check it out and let me know what you think.

**Comment by saumier** [comment]
Looks great.
