### ISSUE TITLE
Fix scenefrancophone errors in Artsdata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-scenesfrancophones#8]
Open the graph in Artsdata using Nebula and check for SHACL violations.  

To view the list of graphs by entity type use an alpha version of Nebula here https://artsdata-nebula-d1ec887e2637.herokuapp.com

Create a list of problems and add them to this issue.

Discuss with Gregory each problem to determine if the data should be fixed before loading into Artsdata or after loading into Artsdata.

Create a SPARQL to fix issues that are agreed should be fixed before loading into Artsdata.

Measure of done
============
The event and other entities can be viewed in the Nebula browser without any errors (marked in red).

**Comment by dev-aravind** [comment]
@saumier  

The SHACL violations are only present in the Events entity, not in Organizations or People. The violations occur in the following fields: eventAttendanceMode, eventStatus and startDate.

Let me know what you think.

**Comment by saumier** [comment]
@dev-aravind Please see if you can fix dates in the main ruby code after the data is loaded into the graph.  This will be a good challenge for you.  Try to use the graph and update all dates ( "@type": "http://schema.org/Date") independently of where they are in the graph.  Please take the time to get familiar with the concept of triples and the internal representation using RDF.rb.  

Do you see the formatting problem? The website has an error in the date format with the timezone offset.  "2024-02-25T08:00:00-0400" is incorrect. The time zone offset is missing a colon: -0400 should be -04:00. Keep in mind the timezone offset changes during the year because of daylight savings. 

I will fix eventAttendanceMode, eventStatus because those are correct, but Artsdata is expecting a URI instead of a Literal https://github.com/culturecreates/artsdata-orion/issues/26.  I looked at the Schema.org context and I see that they are defined as Literals which was not what I was expecting. So I am going to change this everywhere in Artsdata and then the error will go away.

**Comment by saumier** [comment]
@dev-aravind I will let you try to fix the bad dates but after a day I will give you another demo code in Ruby since I realize this is a lot to learn.

There are 2 approaches: using a loop to update, or using a SPARQL.

If you use a loop, you can find the list of dates using `dates = graph.query([nil, RDF::Vocab::SCHEMA.startDate, nil])`

I'll write a full demo tomorrow unless you solve this challenge by then ;-)

**Comment by dev-aravind** [comment]
@saumier I added a SPARQL query to fix the date issue in the demo.rb file that you created. You can find the changes [here](https://github.com/culturecreates/artsdata-planet-scenesfrancophones/pull/13). Let me know what you think.

**Comment by saumier** [comment]
@dev-aravind Please address the requested changes. https://github.com/culturecreates/artsdata-planet-scenesfrancophones/pull/13#pullrequestreview-1805931825.   I added some additional challenges (like find all dates, not just startDate) but please skip these additional challenges if they take more than a day because I want to get the fixed dates sent to Artsdata so we can move on to IPAA.

**Comment by dev-aravind** [comment]
@saumier I added shacl validation and also worked on the sparql query to fix all types of dates. Please look into it and let me know what you think.
